### ISSUE TITLE
[BUG] Dependency Conflicts with Google Jib

### ISSUE THREAD

**Issue by instinet-lewis-boon** [sonatype-nexus-community/scan-gradle-plugin#22]
**Describe the bug**

scan-gradle-plugin breaks Google Jib due to incompatible dependencies. The two problem dependencies (so far) are:

1. Guava
2. a HTTP Client

Both are detailed in the Jib library:

https://github.com/GoogleContainerTools/jib/issues/591
https://github.com/GoogleContainerTools/jib/issues/2183

**To Reproduce**

Create a Spring Initializr project:
- Gradle
- Java
- 2.2.6
- Java 11

Add the following to your build.gradle:

```
id 'org.sonatype.gradle.plugins.scan' version '1.0.0'
id 'com.google.cloud.tools.jib' version '2.1.0'
```
Add some jib config so it doesn't barf at the start:

```
jib {
	container {
		mainClass = 'com.example.demo.DemoApplication'
	}
}
```

Run: `./gradlew jibBuildTar`

```
* What went wrong:
Execution failed for task ':jibBuildTar'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: 'org.apache.http.client.config.RequestConfig$Builder org.apache.http.client.config.RequestConfig$Builder.setNormalizeUri(boolean)'
```
Root Caused By:
```
Caused by: java.lang.NoSuchMethodError: 'org.apache.http.client.config.RequestConfig$Builder org.apache.http.client.config.RequestConfig$Builder.setNormalizeUri(boolean)'
        at com.google.api.client.http.apache.v2.ApacheHttpRequest.<init>(ApacheHttpRequest.java:42)
        at com.google.api.client.http.apache.v2.ApacheHttpTransport.buildRequest(ApacheHttpTransport.java:179)
        at com.google.api.client.http.apache.v2.ApacheHttpTransport.buildRequest(ApacheHttpTransport.java:58)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:889)
        at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:317)
        at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:244)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:139)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:115)
        at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:603)
        at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:417)
        at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:421)
        at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.pullBaseImage(PullBaseImageStep.java:194)
        at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:126)
        at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:56)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
```

**Expected behavior**

Remove `id 'org.sonatype.gradle.plugins.scan' version '1.0.0'` and the command will then successfully create a Docker image.

**Desktop (please complete the following information):**
 - OS: Windows (cmd and WSL)
 - Gradle Version: 6.2.1
 - JVM Version and Flavor: OpenJDK 13
 - Nexus IQ Server Version: 84
 - Version: `id 'org.sonatype.gradle.plugins.scan' version '1.0.0'`

**Additional context**

I can't replicate the Guava issue in the test project. The issue exists in my multimodule project though. It would be nice if Jib shaded their depedencies to resolve the issue, but it doesn't look like that will happen any time soon. Jib is also quite important to our migration to deploying Docker containers and has therefore blocked me from rolling out this plugin, sorry! 😞 

Let me know if you need more details.

**Comment by instinet-lewis-boon** [comment]
Done a bit more digging. `./gradlew buildEnvironment` gives us:

```
classpath
+--- org.springframework.boot:org.springframework.boot.gradle.plugin:2.2.6.RELEASE
|    \--- org.springframework.boot:spring-boot-gradle-plugin:2.2.6.RELEASE
|         +--- org.springframework.boot:spring-boot-loader-tools:2.2.6.RELEASE
|         |    +--- org.springframework:spring-core:5.2.5.RELEASE
|         |    |    \--- org.springframework:spring-jcl:5.2.5.RELEASE
|         |    \--- org.apache.commons:commons-compress:1.19
|         +--- io.spring.gradle:dependency-management-plugin:1.0.9.RELEASE
|         \--- org.apache.commons:commons-compress:1.19
+--- io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:1.0.9.RELEASE
|    \--- io.spring.gradle:dependency-management-plugin:1.0.9.RELEASE
+--- com.google.cloud.tools.jib:com.google.cloud.tools.jib.gradle.plugin:2.1.0
|    \--- gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:2.1.0
|         +--- com.google.http-client:google-http-client:1.34.0
|         |    +--- org.apache.httpcomponents:httpclient:4.5.10
|         |    |    +--- org.apache.httpcomponents:httpcore:4.4.12
|         |    |    +--- commons-logging:commons-logging:1.2
|         |    |    \--- commons-codec:commons-codec:1.11
|         |    +--- org.apache.httpcomponents:httpcore:4.4.12
|         |    +--- com.google.code.findbugs:jsr305:3.0.2
|         |    +--- com.google.guava:guava:28.1-android -> 28.1-jre
|         |    |    +--- com.google.guava:failureaccess:1.0.1
|         |    |    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|         |    |    +--- com.google.code.findbugs:jsr305:3.0.2
|         |    |    +--- org.checkerframework:checker-qual:2.8.1
|         |    |    +--- com.google.errorprone:error_prone_annotations:2.3.2
|         |    |    +--- com.google.j2objc:j2objc-annotations:1.3
|         |    |    \--- org.codehaus.mojo:animal-sniffer-annotations:1.18
|         |    +--- com.google.j2objc:j2objc-annotations:1.3
|         |    +--- io.opencensus:opencensus-api:0.24.0
|         |    |    \--- io.grpc:grpc-context:1.22.1
|         |    \--- io.opencensus:opencensus-contrib-http-util:0.24.0
|         |         +--- io.opencensus:opencensus-api:0.24.0 (*)
|         |         \--- com.google.guava:guava:26.0-android -> 28.1-jre (*)
|         +--- com.google.http-client:google-http-client-apache-v2:1.34.0
|         |    +--- com.google.http-client:google-http-client:1.34.0 (*)
|         |    +--- org.apache.httpcomponents:httpclient:4.5.10 (*)
|         |    \--- org.apache.httpcomponents:httpcore:4.4.12
|         +--- com.google.auth:google-auth-library-oauth2-http:0.18.0
|         |    +--- com.google.auto.value:auto-value-annotations:1.6.6
|         |    +--- com.google.code.findbugs:jsr305:3.0.2
|         |    +--- com.google.auth:google-auth-library-credentials:0.18.0
|         |    +--- com.google.http-client:google-http-client:1.32.1 -> 1.34.0 (*)
|         |    +--- com.google.http-client:google-http-client-jackson2:1.32.1
|         |    |    +--- com.google.http-client:google-http-client:1.32.1 -> 1.34.0 (*)
|         |    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.9 -> 2.9.10
|         |    \--- com.google.guava:guava:28.1-android -> 28.1-jre (*)
|         +--- org.apache.commons:commons-compress:1.19
|         +--- com.google.guava:guava:28.1-jre (*)
|         +--- com.fasterxml.jackson.core:jackson-databind:2.9.10
|         |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.10
|         |    \--- com.fasterxml.jackson.core:jackson-core:2.9.10
|         \--- org.ow2.asm:asm:7.2
\--- org.sonatype.gradle.plugins.scan:org.sonatype.gradle.plugins.scan.gradle.plugin:1.0.0
     \--- org.sonatype.gradle.plugins:scan-gradle-plugin:1.0.0
          +--- com.sonatype.nexus:nexus-platform-api:3.12
          \--- org.sonatype.ossindex:ossindex-service-client:1.3.0
               +--- org.sonatype.ossindex:ossindex-service-api:1.3.0
               |    +--- org.slf4j:slf4j-api:1.7.28
               |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.10
               |    +--- com.google.guava:guava:20.0 -> 28.1-jre (*)
               |    +--- javax.ws.rs:javax.ws.rs-api:2.0.1
               |    \--- org.sonatype.goodies:package-url-java:1.1.1
               +--- javax.inject:javax.inject:1
               +--- org.slf4j:slf4j-api:1.7.28
               +--- org.slf4j:jcl-over-slf4j:1.7.28
               |    \--- org.slf4j:slf4j-api:1.7.28
               +--- com.google.guava:guava:20.0 -> 28.1-jre (*)
               +--- joda-time:joda-time:2.10.4
               +--- com.google.code.gson:gson:2.8.5
               +--- org.apache.httpcomponents:httpclient:4.5.5 -> 4.5.10 (*)
               \--- org.apache.httpcomponents:httpcore:4.4.9 -> 4.4.12
```
`org.sonatype.ossindex:ossindex-service-client:1.3.0` depends on `org.apache.httpcomponents:httpclient:4.5.5`

- [4.5.5](https://github.com/apache/httpcomponents-client/releases/tag/rel%2Fv4.5.5) -> [commit](https://github.com/apache/httpcomponents-client/commit/6f4550ff977a8f497822a17115572dcdb6e715b6) -> [setNormalizeUri missing](https://github.com/apache/httpcomponents-client/blob/6f4550ff977a8f497822a17115572dcdb6e715b6/httpclient/src/main/java/org/apache/http/client/config/RequestConfig.java#L516)
- [4.5.10](https://github.com/apache/httpcomponents-client/releases/tag/rel%2Fv4.5.10) -> [commit](https://github.com/apache/httpcomponents-client/commit/952d8da385e19623a3870d119b724ff82fc5770e) -> [setNormalizeUri present](https://github.com/apache/httpcomponents-client/blob/952d8da385e19623a3870d119b724ff82fc5770e/httpclient/src/main/java/org/apache/http/client/config/RequestConfig.java#L533)

It looks like its being upgraded to 4.5.10 and that should work.

**Comment by guillermo-varela** [comment]
@instinet-lewis-boon I was able to replicate that error using this plugin's version `1.0.1` and when I used the newest `1.0.3` jib ran successfully.

Please try updating to our latest version and let us know if you have any other issue.

**Comment by instinet-lewis-boon** [comment]
Re-added the build config with 1.0.3 and its working perfectly. Thanks for your help @guillermo-varela !
