### ISSUE TITLE
[BUG] NullpointerException when running ossIndexAudit

### ISSUE THREAD

**Issue by rprinsen** [sonatype-nexus-community/scan-gradle-plugin#79]
When running the ossIndexAudit task I get the following NullpointerException:
```

Caused by: java.lang.NullPointerException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.sonatype.gradle.plugins.scan.ossindex.DependencyGraphResponseHandler.getDependenciesMapWithVulnerabilities(DependencyGraphResponseHandler.java:174)
        at org.sonatype.gradle.plugins.scan.ossindex.DependencyGraphResponseHandler.handleOssIndexResponse(DependencyGraphResponseHandler.java:57)
        at org.sonatype.gradle.plugins.scan.ossindex.OssIndexAuditTask.audit(OssIndexAuditTask.java:105)
        ... 123 more
Caused by: java.lang.NullPointerException
        at org.sonatype.gradle.plugins.scan.ossindex.DependencyGraphResponseHandler.hasVulnerabilities(DependencyGraphResponseHandler.java:183)
        at org.sonatype.gradle.plugins.scan.ossindex.DependencyGraphResponseHandler.lambda$hasVulnerabilities$3(DependencyGraphResponseHandler.java:184)
        at org.sonatype.gradle.plugins.scan.ossindex.DependencyGraphResponseHandler.hasVulnerabilities(DependencyGraphResponseHandler.java:185)
        at org.sonatype.gradle.plugins.scan.ossindex.DependencyGraphResponseHandler.lambda$hasVulnerabilities$3(DependencyGraphResponseHandler.java:184)
        at org.sonatype.gradle.plugins.scan.ossindex.DependencyGraphResponseHandler.hasVulnerabilities(DependencyGraphResponseHandler.java:185)
        at org.sonatype.gradle.plugins.scan.ossindex.DependencyGraphResponseHandler.lambda$getDependenciesMapWithVulnerabilities$2(DependencyGraphResponseHandler.java:173)

```
Am using version 2.0.9. Here's my gradle config:
```
ossIndexAudit {
    isDependencyGraph = true
    isPrintBanner = false
}
````

**Comment by guillermo-varela** [comment]
Hi @rprinsen,

Would it be possible for you to please share here a sample project where you are getting that error?


Thanks.
